# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: hued 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "hued"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Conor Horan-Kates"]
  s.date = "2016-06-23"
  s.description = "interact with Philips Hue Hub to control your devices"
  s.email = ["conor.code@gmail.com"]
  s.executables = ["hued"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/hued",
    "hued.gemspec",
    "lib/hued.rb",
    "lib/hued/hub.rb",
    "lib/hued/light.rb",
    "lib/hued/logging.rb",
    "lib/hued/scene.rb",
    "lib/hued/schedule.rb",
    "lib/hued/sensor.rb",
    "log4r.yaml",
    "logs/.exists",
    "resources/api/config",
    "resources/api/description.xml"
  ]
  s.homepage = "http://github.com/chorankates/hued"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Philips Hue HTTP API bindings"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 1.8", "~> 1.8.3"])
      s.add_runtime_dependency(%q<log4r>, [">= 1.1", "~> 1.1.10"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0.1"])
      s.add_development_dependency(%q<rake>, [">= 10.5", "~> 10.5.0"])
    else
      s.add_dependency(%q<json>, [">= 1.8", "~> 1.8.3"])
      s.add_dependency(%q<log4r>, [">= 1.1", "~> 1.1.10"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0.1"])
      s.add_dependency(%q<rake>, [">= 10.5", "~> 10.5.0"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.8", "~> 1.8.3"])
    s.add_dependency(%q<log4r>, [">= 1.1", "~> 1.1.10"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1", "~> 2.0.1"])
    s.add_dependency(%q<rake>, [">= 10.5", "~> 10.5.0"])
  end
end

